# Generated by Django 2.1.8 on 2019-05-08 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('week6', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('writer', models.CharField(max_length=20)),
                ('date', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='Save',
        ),
    ]
