# Generated by Django 2.1.8 on 2019-05-21 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('week6', '0002_auto_20190508_2001'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blog',
            new_name='Message',
        ),
    ]
